//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public int AppUserId { get; set; }
        public string Name { get; set; }
        public string Writer { get; set; }
        public int CategoryId { get; set; }
        public string Image { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Category Category { get; set; }
    }
}
